### ISSUE TITLE
Add "Scroll to Top" Button for Better User Navigation

### ISSUE THREAD

**Issue by TBorundia** [dohinaf/basic-icecream-website#1]
Implement a "Scroll to Top" button to improve user experience by allowing quick navigation back to the top of the webpage. The button should appear when the user scrolls down a certain distance and smoothly scroll back to the top when clicked.

**Comment by Khushi14404** [comment]
I would like to work on this please assign this to me and add labels also

**Comment by dohinafs** [comment]
@Khushi14404 You have been assigned.

**Comment by TBorundia** [comment]
@dohinafs But this issue is opened by me. So it must be assigned to me ?

**Comment by dohinafs** [comment]
@Khushi14404 
Kindly open your issue separately. 
Due to a misunderstanding, as the user who placed the issue didn't mention her interest in being assigned, I assigned it to you but as the assigning works on a first come basis, I'll be unassigning you and assigning it to her as she has cleared the confusion.

**Comment by TBorundia** [comment]
@dohinafs , Thank You so much for understanding !!

**Comment by Riddhi12349** [comment]
hi please assign me this issue
